name: taskify
description: A task management app.
version: 1.0.0+106
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  cloud_firestore: ^5.6.5
  device_info_plus: ^11.3.2
  equatable: ^2.0.7
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_crashlytics: ^4.3.4
  firebase_messaging: ^15.2.4
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  google_sign_in: ^6.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  internet_connection_checker_plus: ^2.7.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  line_awesome_flutter: ^3.0.1
  logger: ^2.5.0
  page_transition: ^2.2.1
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  shared_preferences: ^2.5.2
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15 
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.5
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  mockito: ^5.4.5
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
